### ISSUE TITLE
jasmine tests fail after upgrading rails to 4.2.0 and ruby to 2.2.1

### ISSUE THREAD

**Issue by sp1117** [modeset/teaspoon#344]
Upgraded rails and ruby versions, now teaspoon tests are failing for some reason.

Here's my [Gemfile](http://pastebin.com/2TKiTTTi)

When I run `bundle exec rake teaspoon --trace`, I get this stack trace

```
** Invoke teaspoon (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute teaspoon
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:55871/teaspoon/default
FF..FFFF.F

Failures:

  1) Search: clicking outside search dropdown will empty out the search input box
     Failure/Error: Expected undefined to equal ''.

  2) Search: clicking outside search dropdown will empty out the search results box
     Failure/Error: Expected undefined to equal ''.

  3) Search: #results will return a jQuery Selector for dropdown search results
     Failure/Error: Expected undefined to equal 'search-results hide'.

  4) Search: #input will return a jQuery Selector for dropdown search input
     Failure/Error: Expected undefined to equal 'x'.

  5) Search: #query will return the contents of the dropdown search box
     Failure/Error: Expected undefined to equal 'x'.

  6) Search: #searchRoute will return a route for generating the drop-down
     Failure/Error: Expected '/search/quick?q=' to equal '/search/quick?q=x'.

  7) Search: #emptyResults will empty out the results dropdown
     Failure/Error: Expected undefined to equal ''.

Finished in 0.03800 seconds
10 examples, 7 failures

Failed examples:

teaspoon -s default --filter="Search: clicking outside search dropdown will empty out the search input box."
teaspoon -s default --filter="Search: clicking outside search dropdown will empty out the search results box."
teaspoon -s default --filter="Search: #results will return a jQuery Selector for dropdown search results."
teaspoon -s default --filter="Search: #input will return a jQuery Selector for dropdown search input."
teaspoon -s default --filter="Search: #query will return the contents of the dropdown search box."
teaspoon -s default --filter="Search: #searchRoute will return a route for generating the drop-down."
teaspoon -s default --filter="Search: #emptyResults will empty out the results dropdown."

rake aborted!

/Users/ps032791/.rvm/gems/ruby-2.2.1@record/gems/teaspoon-0.7.9/lib/tasks/teaspoon.rake:5:in `block in <top (required)>'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/ps032791/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/ps032791/.rvm/gems/ruby-2.2.1@record/bin/rake:23:in `load'
/Users/ps032791/.rvm/gems/ruby-2.2.1@record/bin/rake:23:in `<main>'
/Users/ps032791/.rvm/gems/ruby-2.2.1@record/bin/ruby_executable_hooks:15:in `eval'
/Users/ps032791/.rvm/gems/ruby-2.2.1@record/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => teaspoon
```

I didn't not make any changes to the jasmine or teaspoon gems. 

Is there anyone else who is facing a similar issue after the upgrade?

**Comment by mikepack** [comment]
@sp1117 you're using quite an old version of Teaspoon (0.7.9). Can you please try upgrading? There are some upgrade notes in the README: https://github.com/modeset/teaspoon#upgrading

Closing this for now, will happily reopen if you're still experiencing issues after upgrading.

**Comment by sp1117** [comment]
Well, I upgraded teaspoon to 0.8.0 and I get this `Failure/Error: Can't find variable: spyOn`. Did anything change with `spyOn` after this upgrade?

**Comment by mikepack** [comment]
I don't believe so. @jejacks0n are you aware of anything?

**Comment by jejacks0n** [comment]
did jasmine 2.2.0 ship with 0.8, or 0.9?

**Comment by mikepack** [comment]
Nope.

**Comment by jejacks0n** [comment]
@sp1117, then I don't think you're using jasmine 2.2.0 -- which is probably the problem. Probably want to stick to the version you were using before.
