### ISSUE TITLE
Error: ActionView::Template::Error: couldn't find file 'support/chai' with type 'application/javascript'

### ISSUE THREAD

**Issue by schneems** [modeset/teaspoon#419]
I accidentally upgraded from 0.7.4 to 1.1.0. I'm now getting this error:

```
Error: ActionView::Template::Error: couldn't find file 'support/chai' with type 'application/javascript'
/Users/richardschneeman/Documents/projects/codetriage/test/javascript/js_test_helper.coffee:3
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/resolve.rb:64:in `resolve!'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/directive_processor.rb:399:in `resolve'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/directive_processor.rb:207:in `process_require_directive'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/directive_processor.rb:178:in `each'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/directive_processor.rb:178:in `process_directives'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/directive_processor.rb:83:in `_call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/directive_processor.rb:68:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/loader.rb:60:in `block in load'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/loader.rb:44:in `load'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:47:in `yield'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:47:in `load'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/bundle.rb:23:in `block in call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/utils.rb:183:in `dfs'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/bundle.rb:24:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/loader.rb:60:in `block in load'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/loader.rb:44:in `load'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:47:in `yield'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/cached_environment.rb:47:in `load'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/sprockets-3.4.0/lib/sprockets/base.rb:66:in `find_asset'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/suite.rb:53:in `block in asset_tree'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/suite.rb:52:in `each'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/suite.rb:52:in `flat_map'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/suite.rb:52:in `asset_tree'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/suite.rb:33:in `spec_assets'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/app/views/teaspoon/suite/_boot.html.erb:1:in `___sers_richardschneeman__gem_ruby_______gems_teaspoon_______app_views_teaspoon_suite__boot_html_erb__3353771346276396505_2226067340'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/template.rb:145:in `block in render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/template.rb:333:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/template.rb:143:in `render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:47:in `render_partial'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/helpers/rendering_helper.rb:35:in `render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/app/views/teaspoon/suite/show.html.erb:14:in `___sers_richardschneeman__gem_ruby_______gems_teaspoon_______app_views_teaspoon_suite_show_html_erb___3887593104531129198_2246705480'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/template.rb:145:in `block in render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/template.rb:333:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/template.rb:143:in `render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/skylight-0.8.1/lib/skylight/probes/action_view.rb:25:in `render_with_layout'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:14:in `render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:42:in `render_template'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:23:in `render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/rendering.rb:100:in `_render_template'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/rendering.rb:83:in `render_to_body'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/abstract_controller/rendering.rb:25:in `render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:16:in `render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/richardschneeman/.rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:43:in `render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:51:in `serve'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/bundler/gems/omniauth-3c4b79504eb5/lib/omniauth/strategy.rb:185:in `call!'
/Users/richardschneeman/.gem/ruby/2.2.3/bundler/gems/omniauth-3c4b79504eb5/lib/omniauth/strategy.rb:163:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `call'
/Users/richardschneeman/.gem/ruby/2.2.3/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

using

```
  * teaspoon (1.1.1)
  * teaspoon-jasmine (2.3.4)
```

My file looks like this:

```
#= require application
#=require support/sinon
#=require support/chai
#=require support/javascript_helpers.js
```

Are there upgrade guides somewhere?

**Comment by mikepack** [comment]
Chai is [still there](https://github.com/modeset/teaspoon/blob/master/teaspoon-mocha/lib/teaspoon/mocha/assets/support/chai.js). I'll look into this. Thanks for reporting.

**Comment by mikepack** [comment]
Oh, sorry, noticing you're using `teaspoon-jasmine`. Chai ships with `teaspoon-mocha`. Which framework were you using prior to upgrading?

**Comment by mikepack** [comment]
Upgrade notes to 1.0: https://github.com/modeset/teaspoon/blob/master/CHANGELOG.md#100-5415

**Comment by schneems** [comment]
That will probably do it, thanks for the quick response!
