### ISSUE TITLE
CLI command does not work when in CircleCI build environment

### ISSUE THREAD

**Issue by samtgarson** [modeset/teaspoon#441]
When running `bundle exec teaspoon` in CircleCI's build environment, we received the following error message:

```
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:56312/teaspoon/default
Error: Page::NotFound: /teaspoon/default
/home/ubuntu/house_seven/vendor/bundle/ruby/2.1.0/bundler/gems/slices-3f5bc4551e2e/lib/slices/tree.rb:71:in `rescue in find_by_path'
/home/ubuntu/house_seven/vendor/bundle/ruby/2.1.0/bundler/gems/slices-3f5bc4551e2e/lib/slices/tree.rb:69:in `find_by_path'
/home/ubuntu/house_seven/vendor/bundle/ruby/2.1.0/bundler/gems/slices-3f5bc4551e2e/app/controllers/pages_controller.rb:29:in `block in show'
/home/ubuntu/house_seven/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/benchmarkable.rb:38:in `block in benchmark'
/home/ubuntu/house_seven/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
```

This did not occur when we used the Rake task, `rake teaspoon`

**Comment by mikepack** [comment]
Can you please verify that this isn't related to any past CircleCI issues? https://github.com/modeset/teaspoon/issues?utf8=%E2%9C%93&q=CircleCI

**Comment by jejacks0n** [comment]
Closing, unless more information can be provided.
