### ISSUE TITLE
Rails regression upgrading from 4.2.5 to 4.2.5.1

### ISSUE THREAD

**Issue by mockdeep** [modeset/teaspoon#451]
It looks like it might actually be an issue in rails, but when trying to apply the security upgrade teaspoon started failing with the error below. It looks like maybe the `allow_non_precompiled` option stopped working for some reason maybe?

```
Sprockets::Rails::Helper::AssetNotPrecompiled - Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( es5-shim/es5-shim.self.js )` to `config/initializers/assets.rb` and restart your server:
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:350:in `raise_unless_precompiled_asset'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:324:in `digest_path'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:312:in `asset_path'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:90:in `block in resolve_asset_path'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:230:in `block in resolve_asset'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:229:in `resolve_asset'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:89:in `resolve_asset_path'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
  actionview (4.2.5.1) lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
  actionview (4.2.5.1) lib/action_view/helpers/asset_url_helper.rb:245:in `javascript_path'
  actionview (4.2.5.1) lib/action_view/helpers/asset_tag_helper.rb:61:in `block in javascript_include_tag'
  actionview (4.2.5.1) lib/action_view/helpers/asset_tag_helper.rb:59:in `javascript_include_tag'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:144:in `block in javascript_include_tag'
  sprockets-rails (3.0.0) lib/sprockets/rails/helper.rb:142:in `javascript_include_tag'
  teaspoon (1.1.2) app/views/teaspoon/suite/_boot.html.erb:1:in `__home_fletch__rvm_gems_ruby_______gems_teaspoon_______app_views_teaspoon_suite__boot_html_erb__574442300155883327_69899838198140'
```

**Comment by jbrowning** [comment]
Looks like this has already been fixed on `master` via https://github.com/modeset/teaspoon/pull/450.

**Comment by mockdeep** [comment]
Ah, cool.
