### ISSUE TITLE
Error: uninitialized constant Teaspoon::Framework

### ISSUE THREAD

**Issue by mariohmol** [modeset/teaspoon#496]
Error on trying to execute `rails generate teaspoon:install` (tested with bundle exec as well)

I looked at https://github.com/modeset/teaspoon/issues/370 , but all checked and errors persists.

Checked in gemfile.lock and ` teaspoon-mocha` is there.

Any ideas?

thanks

```

[WARNING] Could not load generator "generators/teaspoon/install/install_generator". Error: uninitialized constant Teaspoon::Framework.
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/teaspoon-1.1.5/lib/generators/teaspoon/install/install_generator.rb
:14:in `<class:InstallGenerator>'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/teaspoon-1.1.5/lib/generators/teaspoon/install/install_generator.rb
:6:in `<module:Generators>'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/teaspoon-1.1.5/lib/generators/teaspoon/install/install_generator.rb
:5:in `<module:Teaspoon>'

/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/teaspoon-1.1.5/lib/generators/teaspoon/install/install_generator.rb
:4:in `<top (required)>'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/railties-4.0.1/lib/rails/generators.rb:280:in `block (2 levels) in
lookup'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/railties-4.0.1/lib/rails/generators.rb:276:in `each'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/railties-4.0.1/lib/rails/generators.rb:276:in `block in lookup'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/railties-4.0.1/lib/rails/generators.rb:275:in `each'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/railties-4.0.1/lib/rails/generators.rb:275:in `lookup'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/railties-4.0.1/lib/rails/generators.rb:137:in `find_by_namespace'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/railties-4.0.1/lib/rails/generators.rb:154:in `invoke'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/railties-4.0.1/lib/rails/commands/generate.rb:11:in `<top (required
)>'
/Users/mariohmol/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/railties-4.0.1/lib/rails/commands.rb:48:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

```

**Comment by mariohmol** [comment]
Sorry guys, i figure it out, this worked `RAILS_ENV=test bundle exec rails g teaspoon:install`

wouldnt be good to have this rails_env with bundle in readme? 

bests
